# Generated by Django 4.2 on 2023-04-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=35)),
                ('fname', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
